// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dcagent.proto

#ifndef PROTOBUF_dcagent_2eproto__INCLUDED
#define PROTOBUF_dcagent_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace dagent {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_dcagent_2eproto();
void protobuf_AssignDesc_dcagent_2eproto();
void protobuf_ShutdownFile_dcagent_2eproto();

class MsgDAgent;

// ===================================================================

class MsgDAgent : public ::google::protobuf::Message {
 public:
  MsgDAgent();
  virtual ~MsgDAgent();

  MsgDAgent(const MsgDAgent& from);

  inline MsgDAgent& operator=(const MsgDAgent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgDAgent& default_instance();

  void Swap(MsgDAgent* other);

  // implements Message ----------------------------------------------

  MsgDAgent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgDAgent& from);
  void MergeFrom(const MsgDAgent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional bytes msg_data = 2;
  inline bool has_msg_data() const;
  inline void clear_msg_data();
  static const int kMsgDataFieldNumber = 2;
  inline const ::std::string& msg_data() const;
  inline void set_msg_data(const ::std::string& value);
  inline void set_msg_data(const char* value);
  inline void set_msg_data(const void* value, size_t size);
  inline ::std::string* mutable_msg_data();
  inline ::std::string* release_msg_data();
  inline void set_allocated_msg_data(::std::string* msg_data);

  // @@protoc_insertion_point(class_scope:dagent.MsgDAgent)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_msg_data();
  inline void clear_has_msg_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* msg_data_;
  ::google::protobuf::int32 type_;
  friend void  protobuf_AddDesc_dcagent_2eproto();
  friend void protobuf_AssignDesc_dcagent_2eproto();
  friend void protobuf_ShutdownFile_dcagent_2eproto();

  void InitAsDefaultInstance();
  static MsgDAgent* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgDAgent

// required int32 type = 1;
inline bool MsgDAgent::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgDAgent::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgDAgent::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgDAgent::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 MsgDAgent::type() const {
  // @@protoc_insertion_point(field_get:dagent.MsgDAgent.type)
  return type_;
}
inline void MsgDAgent::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:dagent.MsgDAgent.type)
}

// optional bytes msg_data = 2;
inline bool MsgDAgent::has_msg_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgDAgent::set_has_msg_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgDAgent::clear_has_msg_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgDAgent::clear_msg_data() {
  if (msg_data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_data_->clear();
  }
  clear_has_msg_data();
}
inline const ::std::string& MsgDAgent::msg_data() const {
  // @@protoc_insertion_point(field_get:dagent.MsgDAgent.msg_data)
  return *msg_data_;
}
inline void MsgDAgent::set_msg_data(const ::std::string& value) {
  set_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_data_ = new ::std::string;
  }
  msg_data_->assign(value);
  // @@protoc_insertion_point(field_set:dagent.MsgDAgent.msg_data)
}
inline void MsgDAgent::set_msg_data(const char* value) {
  set_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_data_ = new ::std::string;
  }
  msg_data_->assign(value);
  // @@protoc_insertion_point(field_set_char:dagent.MsgDAgent.msg_data)
}
inline void MsgDAgent::set_msg_data(const void* value, size_t size) {
  set_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_data_ = new ::std::string;
  }
  msg_data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:dagent.MsgDAgent.msg_data)
}
inline ::std::string* MsgDAgent::mutable_msg_data() {
  set_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:dagent.MsgDAgent.msg_data)
  return msg_data_;
}
inline ::std::string* MsgDAgent::release_msg_data() {
  clear_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = msg_data_;
    msg_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MsgDAgent::set_allocated_msg_data(::std::string* msg_data) {
  if (msg_data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msg_data_;
  }
  if (msg_data) {
    set_has_msg_data();
    msg_data_ = msg_data;
  } else {
    clear_has_msg_data();
    msg_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:dagent.MsgDAgent.msg_data)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace dagent

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dcagent_2eproto__INCLUDED
