// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_test_2eproto__INCLUDED
#define PROTOBUF_test_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace test_db {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_test_2eproto();
void protobuf_AssignDesc_test_2eproto();
void protobuf_ShutdownFile_test_2eproto();

class test_coll_person;

// ===================================================================

class test_coll_person : public ::google::protobuf::Message {
 public:
  test_coll_person();
  virtual ~test_coll_person();

  test_coll_person(const test_coll_person& from);

  inline test_coll_person& operator=(const test_coll_person& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const test_coll_person& default_instance();

  void Swap(test_coll_person* other);

  // implements Message ----------------------------------------------

  test_coll_person* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const test_coll_person& from);
  void MergeFrom(const test_coll_person& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional string country = 2;
  inline bool has_country() const;
  inline void clear_country();
  static const int kCountryFieldNumber = 2;
  inline const ::std::string& country() const;
  inline void set_country(const ::std::string& value);
  inline void set_country(const char* value);
  inline void set_country(const char* value, size_t size);
  inline ::std::string* mutable_country();
  inline ::std::string* release_country();
  inline void set_allocated_country(::std::string* country);

  // optional int32 age = 3;
  inline bool has_age() const;
  inline void clear_age();
  static const int kAgeFieldNumber = 3;
  inline ::google::protobuf::int32 age() const;
  inline void set_age(::google::protobuf::int32 value);

  // optional string zipcode = 4;
  inline bool has_zipcode() const;
  inline void clear_zipcode();
  static const int kZipcodeFieldNumber = 4;
  inline const ::std::string& zipcode() const;
  inline void set_zipcode(const ::std::string& value);
  inline void set_zipcode(const char* value);
  inline void set_zipcode(const char* value, size_t size);
  inline ::std::string* mutable_zipcode();
  inline ::std::string* release_zipcode();
  inline void set_allocated_zipcode(::std::string* zipcode);

  // @@protoc_insertion_point(class_scope:test_db.test_coll_person)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_country();
  inline void clear_has_country();
  inline void set_has_age();
  inline void clear_has_age();
  inline void set_has_zipcode();
  inline void clear_has_zipcode();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::std::string* country_;
  ::std::string* zipcode_;
  ::google::protobuf::int32 age_;
  friend void  protobuf_AddDesc_test_2eproto();
  friend void protobuf_AssignDesc_test_2eproto();
  friend void protobuf_ShutdownFile_test_2eproto();

  void InitAsDefaultInstance();
  static test_coll_person* default_instance_;
};
// ===================================================================


// ===================================================================

// test_coll_person

// optional string name = 1;
inline bool test_coll_person::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void test_coll_person::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void test_coll_person::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void test_coll_person::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& test_coll_person::name() const {
  // @@protoc_insertion_point(field_get:test_db.test_coll_person.name)
  return *name_;
}
inline void test_coll_person::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:test_db.test_coll_person.name)
}
inline void test_coll_person::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:test_db.test_coll_person.name)
}
inline void test_coll_person::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:test_db.test_coll_person.name)
}
inline ::std::string* test_coll_person::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:test_db.test_coll_person.name)
  return name_;
}
inline ::std::string* test_coll_person::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void test_coll_person::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:test_db.test_coll_person.name)
}

// optional string country = 2;
inline bool test_coll_person::has_country() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void test_coll_person::set_has_country() {
  _has_bits_[0] |= 0x00000002u;
}
inline void test_coll_person::clear_has_country() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void test_coll_person::clear_country() {
  if (country_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    country_->clear();
  }
  clear_has_country();
}
inline const ::std::string& test_coll_person::country() const {
  // @@protoc_insertion_point(field_get:test_db.test_coll_person.country)
  return *country_;
}
inline void test_coll_person::set_country(const ::std::string& value) {
  set_has_country();
  if (country_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    country_ = new ::std::string;
  }
  country_->assign(value);
  // @@protoc_insertion_point(field_set:test_db.test_coll_person.country)
}
inline void test_coll_person::set_country(const char* value) {
  set_has_country();
  if (country_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    country_ = new ::std::string;
  }
  country_->assign(value);
  // @@protoc_insertion_point(field_set_char:test_db.test_coll_person.country)
}
inline void test_coll_person::set_country(const char* value, size_t size) {
  set_has_country();
  if (country_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    country_ = new ::std::string;
  }
  country_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:test_db.test_coll_person.country)
}
inline ::std::string* test_coll_person::mutable_country() {
  set_has_country();
  if (country_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    country_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:test_db.test_coll_person.country)
  return country_;
}
inline ::std::string* test_coll_person::release_country() {
  clear_has_country();
  if (country_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = country_;
    country_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void test_coll_person::set_allocated_country(::std::string* country) {
  if (country_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete country_;
  }
  if (country) {
    set_has_country();
    country_ = country;
  } else {
    clear_has_country();
    country_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:test_db.test_coll_person.country)
}

// optional int32 age = 3;
inline bool test_coll_person::has_age() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void test_coll_person::set_has_age() {
  _has_bits_[0] |= 0x00000004u;
}
inline void test_coll_person::clear_has_age() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void test_coll_person::clear_age() {
  age_ = 0;
  clear_has_age();
}
inline ::google::protobuf::int32 test_coll_person::age() const {
  // @@protoc_insertion_point(field_get:test_db.test_coll_person.age)
  return age_;
}
inline void test_coll_person::set_age(::google::protobuf::int32 value) {
  set_has_age();
  age_ = value;
  // @@protoc_insertion_point(field_set:test_db.test_coll_person.age)
}

// optional string zipcode = 4;
inline bool test_coll_person::has_zipcode() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void test_coll_person::set_has_zipcode() {
  _has_bits_[0] |= 0x00000008u;
}
inline void test_coll_person::clear_has_zipcode() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void test_coll_person::clear_zipcode() {
  if (zipcode_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    zipcode_->clear();
  }
  clear_has_zipcode();
}
inline const ::std::string& test_coll_person::zipcode() const {
  // @@protoc_insertion_point(field_get:test_db.test_coll_person.zipcode)
  return *zipcode_;
}
inline void test_coll_person::set_zipcode(const ::std::string& value) {
  set_has_zipcode();
  if (zipcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    zipcode_ = new ::std::string;
  }
  zipcode_->assign(value);
  // @@protoc_insertion_point(field_set:test_db.test_coll_person.zipcode)
}
inline void test_coll_person::set_zipcode(const char* value) {
  set_has_zipcode();
  if (zipcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    zipcode_ = new ::std::string;
  }
  zipcode_->assign(value);
  // @@protoc_insertion_point(field_set_char:test_db.test_coll_person.zipcode)
}
inline void test_coll_person::set_zipcode(const char* value, size_t size) {
  set_has_zipcode();
  if (zipcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    zipcode_ = new ::std::string;
  }
  zipcode_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:test_db.test_coll_person.zipcode)
}
inline ::std::string* test_coll_person::mutable_zipcode() {
  set_has_zipcode();
  if (zipcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    zipcode_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:test_db.test_coll_person.zipcode)
  return zipcode_;
}
inline ::std::string* test_coll_person::release_zipcode() {
  clear_has_zipcode();
  if (zipcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = zipcode_;
    zipcode_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void test_coll_person::set_allocated_zipcode(::std::string* zipcode) {
  if (zipcode_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete zipcode_;
  }
  if (zipcode) {
    set_has_zipcode();
    zipcode_ = zipcode;
  } else {
    clear_has_zipcode();
    zipcode_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:test_db.test_coll_person.zipcode)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace test_db

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_test_2eproto__INCLUDED
